In [22]:
import numpy as np

In [7]:
np.array?

### Define an array

In [23]:
a = np.array([1,2,3])
print(a)

[1 2 3]


### Types

In [24]:
print(type(a))
print(type(a[0]))

<type 'numpy.ndarray'>
<type 'numpy.int64'>


Cast it to different types

In [25]:
list_of_types = [float, int, np.float32, np.float64, np.complex64, np.complex128]
for t in list_of_types:
    b = a.astype(t) # this is the casting point
    print(type(b), type(b[0]), b[0])

(<type 'numpy.ndarray'>, <type 'numpy.float64'>, 1.0)
(<type 'numpy.ndarray'>, <type 'numpy.int64'>, 1)
(<type 'numpy.ndarray'>, <type 'numpy.float32'>, 1.0)
(<type 'numpy.ndarray'>, <type 'numpy.float64'>, 1.0)
(<type 'numpy.ndarray'>, <type 'numpy.complex64'>, (1+0j))
(<type 'numpy.ndarray'>, <type 'numpy.complex128'>, (1+0j))


### Numpy arrays are fast!!!

In [26]:
length = 1000
L = range(length)
%timeit [i**2 for i in L]

npa =np.arange(length)
%timeit npa**2

The slowest run took 7.00 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 45 µs per loop
The slowest run took 19.09 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 787 ns per loop


In [27]:
m = np.array([[1,2,3],[4,5,6]], dtype=float)
print(m, type(m))
print(m[0], type(m[0]))
print(m[0,0], type(m[0,0]))
print(m.ndim)
print(m.shape)
print(len(m))

(array([[1., 2., 3.],
       [4., 5., 6.]]), <type 'numpy.ndarray'>)
(array([1., 2., 3.]), <type 'numpy.ndarray'>)
(1.0, <type 'numpy.float64'>)
2
(2, 3)
2


#### Create arrays

In [29]:
shape = (4,5)
np.zeros(shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
a = np.diag(np.arange(5))
print(a)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [34]:
myseed = 666

np.random.seed(myseed)
r1 = np.random.rand(*shape)

np.random.seed(myseed)
r2 = np.random.rand(shape[0], shape[1])

print(np.linalg.norm(r1-r2))

0.0


In [35]:
a = np.diag(np.arange(5))
b = np.diag(a)
print('Matrix:')
print(a)
print('\nDiagonal:')
print(b)

Matrix:
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]

Diagonal:
[0 1 2 3 4]


### Sophisticated indexing

In [36]:
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [37]:
a[0,3:5]

array([3, 4])

In [38]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [39]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [40]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

### Copy and view

In [41]:
a = np.arange(10)
print(a)

b = a[::2]
print(b)

print(np.may_share_memory(a, b))

b[0] = 12
print(b)

# Watch this magic!
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]


In [19]:
a = np.arange(10)

c = a[::2].copy()  # force a copy

c[0] = 12

print(a)
print(np.may_share_memory(a, c))

[0 1 2 3 4 5 6 7 8 9]
False
